name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@release-from-fork # TODO update after Actions release
    permissions:
      contents: write
    with:
      release_prefix: NISAR Docs
      fast_forward_develop: false
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
